import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MAIN from "@/components/layout"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "late-developers",
  description: "Generated by late developers",
};

export default function RootLayout({
  metadata,
  children,
  // pageProps: { session, ...pageProps }
}) {



  return (
    <MAIN geistSans={geistSans} geistMono={geistMono} children={children}/>  
  );
}
